<?php

namespace Tests\Feature\Documentation;

use Tests\TestCase;

/**
 * Covers the L5-Swagger HTTP endpoints.
 *
 * The OpenAPI artefact (storage/api-docs/api-docs.json) is generated by
 * `php artisan l5-swagger:generate`; it is committed to the repo so the
 * UI works without a build step. These tests prove the runtime routes
 * still reach it.
 */
final class SwaggerEndpointsTest extends TestCase
{
    /** /api/documentation renders the Swagger UI HTML page. */
    public function test_swagger_ui_is_reachable(): void
    {
        $response = $this->get('/api/documentation');

        $response->assertOk();
        $response->assertSee('swagger-ui', escape: false);
    }

    /** /docs serves the raw OpenAPI 3.0 JSON used by the UI. */
    public function test_raw_openapi_json_is_served(): void
    {
        $response = $this->get('/docs');

        $response->assertOk();
        $body = $response->json();

        $this->assertSame('3.0.0', $body['openapi']);
        $this->assertSame('Book Library API', $body['info']['title']);
    }

    /**
     * All five Book operations from the controller are present in the
     * generated spec — guards against silently dropping `#[OA\*]`
     * attributes during a future refactor.
     */
    public function test_openapi_includes_all_five_book_operations(): void
    {
        $body = $this->get('/docs')->json();

        $this->assertArrayHasKey('/api/v1/books', $body['paths']);
        $this->assertArrayHasKey('/api/v1/books/{book}', $body['paths']);

        $this->assertArrayHasKey('get', $body['paths']['/api/v1/books']);
        $this->assertArrayHasKey('post', $body['paths']['/api/v1/books']);
        $this->assertArrayHasKey('get', $body['paths']['/api/v1/books/{book}']);
        $this->assertArrayHasKey('patch', $body['paths']['/api/v1/books/{book}']);
        $this->assertArrayHasKey('delete', $body['paths']['/api/v1/books/{book}']);
    }

    /** All four shared component schemas are declared (Book + payload + 2 errors). */
    public function test_openapi_declares_all_shared_schemas(): void
    {
        $body = $this->get('/docs')->json();

        $schemas = array_keys($body['components']['schemas']);
        $this->assertContains('Book', $schemas);
        $this->assertContains('BookPayload', $schemas);
        $this->assertContains('ErrorMessage', $schemas);
        $this->assertContains('ValidationError', $schemas);
    }
}
